InterfacePrincipal:

<InterfacePrincipal>:
    orientation: "vertical"
    Label:
        text: "Titulo"

    Conteudo:

    Label:
        text: "Rodapé"

<Conteudo>:
    Accordion:
        orientation: "vertical"
        AccordionItem:
            Label:
                text: "Conteudo"
        AccordionItem:
            Label:
                text: "Conteudo"
        AccordionItem:
            Label:
                text: "Conteudo"